name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_NAME: ascend-avoid
  RESOURCE_GROUP: DefaultResourceGroup-EUS
  IMAGE_NAME: ascend-avoid
  ACR_NAME: portfoliodrewclarkazure
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build application
        run: npm run build

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ASCENDAVOID_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ASCENDAVOID_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ASCENDAVOID_AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update Container Image (with retry)
        run: |
          RETRY_COUNT=5
          RETRY_DELAY=30

          for i in $(seq 1 $RETRY_COUNT); do
            echo "Attempt $i to update the container image..."

            az containerapp update \
              --name ${{ env.APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} && break

            if [ $i -eq $RETRY_COUNT ]; then
              echo "Failed to update the container image after $RETRY_COUNT attempts."
              exit 1
            fi

            echo "Operation in progress. Waiting $RETRY_DELAY seconds before retry..."
            sleep $RETRY_DELAY
          done

      - name: Update Ingress (with retry)
        run: |
          RETRY_COUNT=5
          RETRY_DELAY=30

          for i in $(seq 1 $RETRY_COUNT); do
            echo "Attempt $i to configure ingress..."

            az containerapp ingress update \
              --name ${{ env.APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --type external \
              --target-port 3000 \
              --transport auto && break

            if [ $i -eq $RETRY_COUNT ]; then
              echo "Failed to configure ingress after $RETRY_COUNT attempts."
              exit 1
            fi

            echo "Operation in progress. Waiting $RETRY_DELAY seconds before retry..."
            sleep $RETRY_DELAY
          done

      - name: Update Health Probes (with retry)
        run: |
          RETRY_COUNT=5
          RETRY_DELAY=30

          for i in $(seq 1 $RETRY_COUNT); do
            echo "Attempt $i to set health probes..."

            # Dump current config to JSON
            az containerapp show \
              --name ${{ env.APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              -o json > current_config.json

            # Patch the JSON using jq:
            #  1) Overwrite the container's image property to ensure the container has an image specified
            #  2) Overwrite probes with our startup probe definition
            # Note: We use --arg to safely embed the environment-based image into JSON
            jq --arg newImage "${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}" '
              .properties.template.containers[0].image = $newImage
              |
              .properties.template.containers[0].probes = [
                {
                  "type": "startup",
                  "httpGet": {
                    "path": "/",
                    "port": 3000,
                    "httpHeaders": []
                  },
                  "initialDelaySeconds": 30,
                  "periodSeconds": 10,
                  "timeoutSeconds": 5,
                  "successThreshold": 1,
                  "failureThreshold": 30
                }
              ]
            ' current_config.json > updated_config.json

            # Apply the patched file with a single containerapp update
            az containerapp update \
              --name ${{ env.APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --file updated_config.json && break

            if [ $i -eq $RETRY_COUNT ]; then
              echo "Failed to set health probes after $RETRY_COUNT attempts."
              exit 1
            fi

            echo "Operation in progress. Waiting $RETRY_DELAY seconds before retry..."
            sleep $RETRY_DELAY
          done

      - name: Wait for deployment to stabilize
        run: |
          echo "Waiting for deployment to stabilize..."
          sleep 30

      - name: Update verification URL in package.json
        run: |
          # Get the app URL
          APP_URL=$(az containerapp show --name ${{ env.APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query properties.configuration.ingress.fqdn -o tsv)
          echo "Container App URL: https://$APP_URL"

          # Update the verify-deployment:azure script with the correct URL
          sed -i "s|https://ascend-avoid.azurewebsites.net|https://$APP_URL|g" package.json

      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          npm run verify-deployment:azure
