name: Azure Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ascend-avoid'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './dist'
          
      - name: Verify deployment
        run: |
          export VERIFY_URL=https://ascend-avoid.wittyhill-c50d4888.eastus.azurecontainerapps.io
          export VERIFY_TIMEOUT=120000
          export VERIFY_RETRIES=10
          export VERIFY_RETRY_DELAY=15000
          export VERIFY_HEALTH_PATH=/
          export VERIFY_ACCEPTABLE_STATUS_CODES=200-299,301,302,303,307,308
          node scripts/verify-deployment.js
