name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  build-and-deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: aiandrew631
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: aiandrew631/ascend-avoid:latest
          cache-from: type=registry,ref=aiandrew631/ascend-avoid:buildcache
          cache-to: type=registry,ref=aiandrew631/ascend-avoid:buildcache,mode=max
      
      # Azure Login and Deployment
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Deploy to Azure Container App
      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          containerAppName: ascend
          resourceGroup: DefaultResourceGroup-EUS
          imageToDeploy: docker.io/aiandrew631/ascend-avoid:latest
          targetPort: 3000
          ingress: external
          environmentVariables: >
            NODE_ENV=production
            PORT=3000
          enableDapr: false
          maxReplicas: 5
          minReplicas: 1
          revisionMode: single
